version: 0.2


phases:
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo 'Compiling the Java Code'
      - javac -cp . HelloWorld.java
  post_build:
    commands:
      - echo "Would deploy here"
      - echo "666"
artifacts:
  type: zip
  files:
    - 'HelloWorld.class'
