name: hello-world
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - run: echo "Hello World!"
      - run: javac -cp . HelloWorld.java
      - run: echo "Done!"
