name: hello-world
on: workflow_dispatch
# on:
#   push:
#     branches:
#       - test
jobs:
  my-job:
    runs-on: 	ubuntu-latest
    env:
      version8: '8'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: pwd
      - run: ls
      - run: docker build .
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJSON(github) }}
#         run: echo "$GITHUB_CONTEXT"
#       - name: Dump job context
#         env:
#           JOB_CONTEXT: ${{ toJSON(job) }}
#         run: echo "$JOB_CONTEXT"
#       - name: Echo version of aws-cli
#         uses: hannut91/aws-cli@1.18.43
#         with:
#           args: --version
#       - run: env
#       - name: Setup java
#         id: stepjava
#         uses: actions/setup-java@v2
#         with:
#           distribution: 'adopt'
#           java-version: ${{ env.version8 }}
#           check-latest: true
#         env:
#           version: '11'
#       - run: echo "${{ steps.stepjava.outputs.version  }}"
#       - name: Dump version
#         env:
#           version: ${{ steps.stepjava.outputs.version  }}
#         run: echo "$version"
#       - uses: xinw0911/hello-world@4423a356715630def9b8dc3967c00947086eeeff
#         id: hello
#         with:
#           who-to-greet: ${{ env.who }}
#         env:
#           who: ${{ env.version8 }}
#       - name: Dump steps context
#         env:
#           STEPS_CONTEXT: ${{ toJSON(steps) }}
#         run: echo "$STEPS_CONTEXT"
#       - run: ls
