name: hello-world
on: workflow_dispatch
# on:
#   push:
#     branches:
#       - test
jobs:
  my-job:
    runs-on: 	self-hosted
    steps:
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJSON(github) }}
#         run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
#       - name: Echo version of aws-cli
#         uses: hannut91/aws-cli@1.18.43
#         with:
#           args: --version
      - run: env

#       - run: ls -al ../..
      - name: Setup java
        id: stepjava
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - run: echo "${{ step1.outputs.version  }}"
      - name: Dump version
        env:
          version: ${{ step1.outputs.version  }}
        run: echo "$version"
