name: hello-world
on: workflow_dispatch
# on:
#   push:
#     branches:
#       - test
jobs:
  my-job:
    runs-on: 	ubuntu-latest
    steps:
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJSON(github) }}
#         run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
#       - name: Echo version of aws-cli
#         uses: hannut91/aws-cli@1.18.43
#         with:
#           args: --version
      - run: env

#       - run: ls -al ../..
      - name: Setup java
        id: stepjava
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.version }}
          check-latest: true
        env:
          version: '11'
      - run: echo "${{ steps.stepjava.outputs.version  }}"
      - name: Dump version
        env:
          version: ${{ steps.stepjava.outputs.version  }}
        run: echo "$version"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: ${{ env.who }}
        env:
          who: 'xwana'
