name: hello-world
on: workflow_dispatch
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: Echo version of aws-cli
        uses: hannut91/aws-cli@1.18.43
        with:
          args: help
#       - uses: actions/checkout@v2
#       - name: Setup java
#         uses: actions/setup-java@v2
#         with:
#           distribution: 'adopt'
#           java-version: '11'
#           check-latest: true
      - name: post output
        run: echo "Hello World!"
#       - run: javac -cp . HelloWorld.java
      - run: echo "Done!"
