name: test-pipeline-artifact-mapping

on: 
  workflow_dispatch:
# on:
#   push:
#     branches:
#       - test
permissions:
  id-token: write
  contents: read
jobs:
  my-job:
    runs-on: 	ubuntu-latest
    env:
      version8: '8'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#       - name: Echo version of aws-cli
#         uses: hannut91/aws-cli@1.18.43
#         with:
#           args: --version
#       - run: env
      - name: Setup java
        id: stepjava
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.version8 }}
          check-latest: true
        env:
          version: '11'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::834197531540:role/test-deployServiceRoleBA1AC55C-as2CD4zNVdgC
          aws-region: us-east-1
      - run: |
               aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 834197531540.dkr.ecr.us-east-1.amazonaws.com
               docker build -t testmapping .
               docker tag testmapping:latest 834197531540.dkr.ecr.us-east-1.amazonaws.com/testmapping:latest
               docker push 834197531540.dkr.ecr.us-east-1.amazonaws.com/testmapping:latest   
      - name: compile
        run: javac HelloWorld.java
      - run: ls
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: HellowWorld.class
          retention-days: 5
      - run: aws s3 cp HellowWorld.class s3://xwana-iad-test-bucket/HellowWorld.class
